<Project>
    <PropertyGroup>
        <!-- Megadot current version is 4.5.1, and the game won't load your .pck if the Godot version used is newer. -->
        <!-- MegaDot / Godot 4.5.1 mono executable used for export-pack when publishing -->
        <GodotPath>C:\Users\pytho\megadot\MegaDot_v4.5.1-stable_mono_win64.exe</GodotPath>

        <!-- If sts2 is not found automatically, uncomment the following and set it manually -->
        <!--<Sts2Path>/home/landmaster/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Slay the Spire 2</Sts2Path>-->
    </PropertyGroup>
</Project>